
spring:
  datasource:
    url: jdbc:h2:mem:bank;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
server:
  port: 8080

# External services
fraud:
  base-url: http://localhost:9090
